### ISSUE TITLE
View command fix UI spacing for no tier

### ISSUE THREAD

**Issue by iamdiluxedbutcooler** [AY2425S1-CS2103T-T14-4/tp#119]
Further improvement from #104 , currently got weird spacing when a person has no tier. Tried solve a bit but found our would take a while to figure out, planned to add condition check for tier NA in PersonDetailPanel.java and edit its related .fxml and .css file.

<img width="402" alt="Screenshot 2567-10-23 at 04 24 52" src="https://github.com/user-attachments/assets/3038b556-4609-4820-ac80-993dfd6c2e75">

**Comment by itsme-zeix** [comment]
A Vbox containing just the tiers might work here maybe? minheight = 0
