### ISSUE TITLE
All fields could be truncated

### ISSUE THREAD

**Issue by FionaQY** [AY2425S1-CS2103T-T14-4/tp#158]
Currently if any of the fields other than remark are too long, they are not truncated which decreases readability. Truncating all fields would greatly increase readability and if there is any missing information, users can use the ViewCommand instead.

<img width="1181" alt="image" src="https://github.com/user-attachments/assets/2b2c82b2-ec36-4616-b400-69be9c6f93ee">

**Comment by itsme-zeix** [comment]
@colinhia Could also add a "comment" icon beside remarks while fixing this!
