### ISSUE TITLE
[PE-D][Tester A] UG PDF Formatting

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T14-4/tp#240]
You may want to consider adding page breaks to prevent content from being cut off at weird places when being downloaded as a PDF to make it look neater in a PDF format and improve users' reading experience.

Some examples are: 
![image.png](https://raw.githubusercontent.com/Fluffykan/ped/main/files/27f51f11-9bb4-449b-b418-331898088563.png)

![image.png](https://raw.githubusercontent.com/Fluffykan/ped/main/files/2fa8d4c8-eed4-4043-8712-97f2c86355b5.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Fluffykan/ped#2

**Comment by colinhia** [comment]
Duplicate of #234
