### ISSUE TITLE
[PE-D][Tester A] APP Inaccurate Error Message - Add Command

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T14-4/tp#262]
![image.png](https://raw.githubusercontent.com/Fluffykan/ped/main/files/eb3bd885-3e70-4383-89d3-ba88be95960d.png)

Currently, an empty remark field causes the system to notify the user that the remarks can only contain ASCII characters.
Perhaps a message could include asking the user to remove the `r/` tag if they dont intend to include remarks

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Fluffykan/ped#6

**Comment by ZShunRen** [comment]
Thank you for the bug report. We acknowledge that in this case, the error message could be more helpful. However, it is stated in our user guide that all arguments cannot be empty. Thus, although this error can be improved in clarity, users should be informed about this. 
![image](https://github.com/user-attachments/assets/4840fcea-7030-4e80-acb8-9ecf12354f03)
