### ISSUE TITLE
[PE-D][Tester E] Improving readability of UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T14-4/tp#273]
This concerns with the `Getting Started` Portion of the UG.

![image.png](https://raw.githubusercontent.com/t-leongchuan/ped/main/files/23919bea-bdf4-4b53-9d9e-a2146e0eea2c.png)

This may come of as opinionated but below are some improvements for the team to consider to improve the ease of readability (For bank agent/target audience):

1) Step 1 of installing Java

I think that by having an additional line along the lines of what Java is 
(For example, `Java is a software platform that lets you run certain types of application, such as .jar files` Learn more here [hyperlink])
would give them a better understanding of **why** java is needed for the application

2) Step 2 

Might be great for the users to have an additional info box informing them of what a `.jar` file is to reassure them that it is not a malicious program
(For example, a `.jar` file can be considered a zipped folder that contains the essentials to run our program, which **requires** java)

---

The rest of the steps seems fine for the target audience to follow along.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: t-leongchuan/ped#10

**Comment by iamdiluxedbutcooler** [comment]
Thank you for your thoughtful suggestions to improve the guide! We appreciate your attention to detail and your perspective on enhancing user readability.

After careful consideration, we believe that adding in-depth explanations about Java and .jar files is somewhat outside the scope of this guide. Our goal is to keep the setup instructions streamlined and focused. Additionally, in discussions with other groups during our recent CS2101 session, there were no concerns raised regarding the clarity of the current "Getting Started" instructions.

That said, we do appreciate the value of your input and will keep it in mind for potential future iterations of the guide. Thanks again for taking the time to share your feedback!
