### ISSUE TITLE
[PE-D][Tester E] Abusing Edit Command to create a 'Duplicate Person`

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T14-4/tp#276]
![image.png](https://raw.githubusercontent.com/t-leongchuan/ped/main/files/6b9ec644-b4f7-4c65-b6c1-e1755cc4e2d7.png)

It is possible to use the edit command on a separate person to 'create' a duplicate of a person that already exists in the contact list.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: t-leongchuan/ped#12

**Comment by colinhia** [comment]
Typo in the email field, person 6 had email johnnd@example.com; person 7 has email johnd@example.com (one less 'n' character).
