### ISSUE TITLE
[PE-D][Tester D] Repetitive user stories

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T14-4/tp#278]
![Screenshot 2024-11-08 at 5.56.34 PM.png](https://raw.githubusercontent.com/siriousguy/ped/main/files/715e0819-f752-4aca-9226-a6cbce4c50f4.png)
first and last rows are basically the same 

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: siriousguy/ped#17

**Comment by FionaQY** [comment]
duplicate of #265
