### ISSUE TITLE
[PE-D][Tester D] Exit behavior differs from the User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T14-4/tp#297]
Unnoticeable brief delay in exiting the appplication.

![Screenshot 2024-11-08 at 7.14.02 PM.png](https://raw.githubusercontent.com/siriousguy/ped/main/files/040b1650-1b36-4d28-a3de-13b77af64b66.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: siriousguy/ped#21

**Comment by FionaQY** [comment]
we would like to reject this bug as "a brief delay" is subjective and this is included to encourage users to worry less when there is any delay on their end.
