### ISSUE TITLE
[PE-D][Tester A] UG Duplicate Examples - Edit Command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T14-4/tp#300]
![image.png](https://raw.githubusercontent.com/Fluffykan/ped/main/files/b02225bb-0f48-403d-b470-e7c8459d2a7c.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Fluffykan/ped#12

**Comment by FionaQY** [comment]
duplicate issue
