### ISSUE TITLE
[PE-D][Tester D] error message does not match the error for filter tier and status

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T14-4/tp#304]
Filter does not catch when tier and status are not part of the predefined ones.

![Screenshot 2024-11-08 at 7.44.33 PM.png](https://raw.githubusercontent.com/siriousguy/ped/main/files/30d6249f-9235-41e8-8cec-e2b5608fadfb.png)
![Screenshot 2024-11-08 at 7.46.02 PM.png](https://raw.githubusercontent.com/siriousguy/ped/main/files/2bb80320-2efc-481e-bde9-fb7feb39e82e.png)

![Screenshot 2024-11-08 at 7.44.13 PM.png](https://raw.githubusercontent.com/siriousguy/ped/main/files/596a869a-29a2-44e6-a333-13627d2e03ee.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: siriousguy/ped#22

**Comment by ZShunRen** [comment]
Thank you for bringing this to our attention! We've carefully reviewed this report and would like to explain our current design approach.

The filter command is intentionally designed to work through substring matching across all fields. While we acknowledge there are some inconsistencies with the p/ and e/ flags (which we plan to update for consistency), the current tier filtering behavior actually aligns with our core design philosophy.

One benefit of this approach is its flexibility – users can freely search without needing to know the exact predefined values. If they enter a substring that doesn't match any tiers, the empty result set effectively helps them understand there are no matches, similar to how search works in other contexts.

While we appreciate the suggestion to add an error message, we believe the current behavior provides a simple, consistent experience.
